sequenceDiagram
    participant Utilisateur
    participant ThingController
    participant Light
    participant HomeSystem

    Utilisateur->>+ThingController: click Toggle Light
    ThingController->>Light:setLightOn()
    Light->>Light:update state
    Light->>HomeSystem:Notifier listener
    HomeSystem->> HomeSystem: MAJ Log
    Light->>ThingController: MAJ Etat
    ThingController-->-Utilisateur: affiche resultat

